name = "WebP"
uuid = "e3aaa7dc-3e4b-44e0-be63-ffb868ccd7c1"
authors = ["Jesper Stemann Andersen"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
libwebp_jll = "c5f90fcd-3b7e-5836-afba-fc50a0988cb2"

[compat]
CEnum = "0.4, 0.5"
julia = "1"
libwebp_jll = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
