[general]
library_name = "libwebp"
library_names = { "/demux\\.h$" = "libwebpdemux", "/mux\\.h$" = "libwebpmux", "/mux_types\\.h$" = "libwebpmux" }
output_file_path = "../src/Wrapper.jl"
module_name = "Wrapper"
jll_pkg_name = "libwebp_jll"
epilogue_file_path = "header_only_wrappers_epilogue.jl"
export_symbol_prefixes = ["WebP"]
